### PR TITLE
Rxswift deprecations

### PR DESCRIPTION
**Pull request by reejosamuel**
Running the project threw a lot of deprecations, decided to save all of us some time.
Update `bindTo(inst)` to `bind(to: inst)`
Update   `addDisposableTo(inst)` to `disposed(by: inst)`

### CODE REVIEW

**Comment by devxoul** [comment]
@reejosamuel, thanks for your work but I'm currently moving to a new code base (#4). I'll use new RxSwift syntax on that :)

**Comment by reejosamuel** [comment]
The pull request was to your new branch

**Comment by devxoul** [comment]
@reejosamuel oh man cool. I didn't realize that so I pushed many changes to that branch :( Could you please resolve the conflicts? Then I'll merge this 👍

**Comment by devxoul** [comment]
#4 is merged into the `master` branch so I changed your PR's target branch to `master`.

**Comment by devxoul** [comment]
@reejosamuel, thanks for your contribution! :tada:

**Pull request merged**
